backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - label: "Posts"
    name: "post"
    folder: "posts"
    create: true
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}